### ISSUE TITLE
Kindle Compatibility

### ISSUE THREAD

**Issue by abdurrosyidhandoyo** [jrfonseca/jmdict-kindle#1]
Can this plugin be used on kindle device outside paperwhite?

**Comment by jrfonseca** [comment]
Strictly speaking, jmdict-kindle is not really a Kindle plugin -- it's just a dictionary ebook.

You can try to download and install on any '_e-ink_ Kindle (just follow the [PaperWhite instructions](https://github.com/jrfonseca/jmdict-kindle#kindle-paperwhite)).  I'd expect it to work on the newer generation of _e-ink_ Kindles after Paperwhite, such as Kindle Voyage, Kindle Oasis, or even the new generations of ordinary Kindle.

I don't expect it to work on Kindle Fire or any other Android based Kindle reader.

What Kindle device and software version do you have?  (See instructions of how to check this  [here](http://www.amazon.com/gp/help/customer/display.html?nodeId=201608150).)
