### ISSUE TITLE
Dictionary loaded onto Kindle Paperwhite is not working

### ISSUE THREAD

**Issue by roboticsbrian** [jrfonseca/jmdict-kindle#11]
I loaded the `combined.mobi` from [this release](https://github.com/jrfonseca/jmdict-kindle/releases/tag/2.0.20210221) into my Kindle Paperwhite (Kindle 5.13.4) but it is not shown in the list of Japanese dictionaries:

![image](https://user-images.githubusercontent.com/47238439/110224394-95913500-7f1e-11eb-88b7-6bb88b83eb6d.png)

![image](https://user-images.githubusercontent.com/47238439/110224487-5f07ea00-7f1f-11eb-9526-1c0386988a77.png)

I have already tried restarting the Kindle.

**Comment by roboticsbrian** [comment]
Upon further testing, the `jmdict.mobi` and `jmnedict.mobi` files from the latest release work, but not the `combined.mobi` file. 

I also tested the files from [2.0.20200708](https://github.com/jrfonseca/jmdict-kindle/releases/tag/2.0.20200708) and the `combined.mobi` from that release doesn't work either.

**Comment by jrfonseca** [comment]
/cc @mymro 

Could you also try https://github.com/jrfonseca/jmdict-kindle/releases/tag/2.0.20190608 ? It's the first with `combined.mobi`.  This way we can know whether it's a regression or not.

Offhand, I suspect the problem with `combined.mobi` might be its sheer size.

**Comment by mymro** [comment]
Unfortunately I cannot reproduce the issue. Both my Kindle Oasis 2 (5.13.4) and Kindle Paperwhite 2 (5.12.2) can work with the new and old version of the combined dictionary just fine.

**Comment by mymro** [comment]
@roboticsbrian It seems your Kindle loaded the dictionary also just fine. It is named "Japanese-English Dictionary" and visible in your screenshot
