### ISSUE TITLE
include notes

### ISSUE THREAD

**Issue by Thermospore** [jrfonseca/jmdict-kindle#14]
eg http://www.edrdg.org/jmdictdb/cgi-bin/entr.py?svc=jmdict&sid=&q=2120780.1
![image](https://user-images.githubusercontent.com/35350819/117930398-672b2f80-b2aa-11eb-978a-da8684d49e37.png)

**Comment by mymro** [comment]
@Thermospore Around Christmas I should have time to look into implementing this
