### ISSUE TITLE
Pitch information README

### ISSUE THREAD

**Issue by Ceffa93** [jrfonseca/jmdict-kindle#16]
I love the new addition of pitch information in the dictionary, however I have troubles understanding it.
The up and down arrows are very clear, but the underscore really confuses me.
I tried to google but it is not helping.

I think it would be useful if you could add a section in the readme that briefly explains the notation.

**Comment by jrfonseca** [comment]
@mymro, what do you think?

**Comment by Ceffa93** [comment]
I assume that many users are not programmers and just jump to the download tab, so it could be useful to make a separate Guide document which also gets added to the release zip.

**Comment by mymro** [comment]
@Ceffa93 I am not completely happy with the formatting, but I was unable to find a format for "high". "Low" currently is denoted by the underline, but there is no overline on Kindle. As a result, "high" is denoted by having not format at all.

 If you have a better idea for formatting, it would be great if you could share it.

**Comment by Ceffa93** [comment]
@mymro
I'm not an expert in japanese pitch accents so maybe it is a problem in my understanding, but shouldn't arrows be enough?
No arrows means flat, otherwise it has a pitch change.
My understanding is that there is no absolute concept of high and low, it is just relative. 
A completely flat word is neither high or low. 

I don't remember which word it was, but I remember seeing one that had 4 kana, with the following signs:
Underscore on first kana, arrow after second kana, underscore under third and forth kana.
I really don't understand the underscores there, my expectations is that anything before the arrow is high, anything after the arrow is low.

Maybe all of this confusion is caused by me having not understood phonetics rules, in that case please just let me know 😅

**Comment by mymro** [comment]
@Ceffa93 Japanese pitch is a bit more complex than you think:

In reality there is no true high or true low. It is better to just remember the accented kana. If you now the accented kana, you know the pitch. The following is the explanation for standard Japanese [wikipedia](https://en.wikipedia.org/wiki/Japanese_pitch_accent):

1. If the accented kana is the first one, then the pitch is high on the first kana and quickly drops on the second HꜜL, HꜜL-L, HꜜL-L-L, HꜜL-L-L-L, ...
2. If the accented kana is somewhere in the middle then we start low and slowly rise in pitch until we reach the maximum at the accented kana and quickly drop afterwards L-Hꜜ, L-HꜜL, L-H-HꜜL, L-H-H-HꜜL-L, ...
3. If the accented kana is at the end we start low and slowly rise in pitch until we reach the maximum at the last kana. The drop then usually happens at the following particle, but there is none in the word itself L-H, L-H-H, L-H-H-H, L-H-H-H-H, ... .
4. If there is no accent, we still start low and rise on the first one or two kana to something that is between high or low and remain there.

The arrow itself does not mean everything before the arrow is high, it just means there is a drop and at least the kana with the arrow is high. 

For your example the pitch would be L-HꜜL-L (2.). This would mean the second kana is the accented one.

**Comment by Ceffa93** [comment]
![images (87)](https://user-images.githubusercontent.com/5756557/143732214-bba36de6-386b-4b55-857c-70e83b5b3d0c.jpeg)
I see, I had in mind this type of notation when I wrote the message.
This notation can be encoded as just arrows before a change in pitch.
Your notation (or the one encoded in the dictionary) has a different take on it, but I think they are both valid.
Thanks for the explanation, now I know how I should read them!

**Comment by Ceffa93** [comment]
In my example, it would be encoded as:
X UP X DOWN X X

**Comment by Ceffa93** [comment]
@mymro 
Sorry for the many messages, I have another question:
I just found a couple words that have another phonetic symbol next to them, a tiny circle.
What is the meaning of it?

**Comment by mymro** [comment]
@Ceffa93 Not quite sure myself. It is supposed to be a nasal sound. But apart from that ...
