### ISSUE TITLE
Brilliant dictionary! Looking forward to a version included Japanese proper names

### ISSUE THREAD

**Issue by lippmann** [jrfonseca/jmdict-kindle#2]
Thank you so much for bring us such a great J-E dictionary. In my opinion, this is the best Japanese dictionary online for Kindle . 

A minor advice, it would be even better if it includes Japanese proper names from ENAMDICT. I know you've been working on it. Hope you could release it soon.

Cheers.

**Comment by jrfonseca** [comment]
Thanks.  It's good to know this is useful for others.

Yes, I haven't spent much time improving this dictionary lately, but I agree proper Japanese names could be quite useful.

**Comment by mymro** [comment]
I have just created a pull request which will add example sentences and names.

**Comment by jrfonseca** [comment]
https://github.com/jrfonseca/jmdict-kindle/pull/4 was merged.  I'll soon make a release which will include the final dictionaries.
