### ISSUE TITLE
Improve pitch diagram

### ISSUE THREAD

**Issue by seanblue** [jrfonseca/jmdict-kindle#26]
I understand if this isn't something you want to consider, but I find the pitch notation used in the dictionary unintuitive and think it can be improved.

For example:
![image](https://user-images.githubusercontent.com/5884067/202339766-62e8d08d-cd7a-454a-9949-c11a4c7fd6f7.png)
![image](https://user-images.githubusercontent.com/5884067/202339660-ea14a299-bdec-4d5a-a621-6b8186752f47.png)

I think the reason I find this difficult is because I'm used to seeing the lines on the top rather than the bottom, so what's shown in this dictionary is the opposite of my expectation. For example, here's what Yomichan does:
![image](https://user-images.githubusercontent.com/5884067/202339523-69e5d6de-3bdc-47f8-a29e-5d28c74ae5d7.png)
![image](https://user-images.githubusercontent.com/5884067/202339701-47135059-b550-471f-8980-84263c44afa4.png)

Is it possible to show the lines on top as Yomichan does, and if so would you consider changing to this? (I feel like this is the more standard way to show it when using lines, so I suspect it's simply not possible, but if it *is* possible that would be great.)

Regardless of the above, would you consider adding in the other fairly standard notation of `[X]` *in addition to* the line notation (as shown in the above screenshots)? For example, `[0]` represents heiban and in all other cases the number in the brackets represents the mora after which the pitch drops. For those of us familiar with pitch accent, this notation is succinct and can be understood intuitively.

**Comment by jrfonseca** [comment]
I don't have a strong opinion here.  @mymro's the expert here.

In terms of what's possible to achieve on a Kindle, one can refer to the tables on [Attributes and Tags Supported by Enhanced Typesetting](https://kdp.amazon.com/en_US/help/topic/GB5GDY7WAJDN9GFK).  It does mention

> text-decoration: line-through, **overline**, **underline**"

so what you suggest might be technically feasable.  But the lines it won't be dotted, as that same page explicitly mentions the `dotted` attribute is ignored, and that's the attribute required to get dotted lines per this [StackOverflow discussion](https://stackoverflow.com/a/15252701).

One would need to actually test on a Kindle to be sure it works in practice, i.e., that the lines are rendered, and are do not overlap the Kanji characters.

**Comment by mymro** [comment]
@seanblue @jrfonseca I initially tried overlines (I also prefer them), but I was unable to get it working. We can easily try it again. It should only require a change in the css file

**Comment by mymro** [comment]
We already add an overline, but it is ignored by kindle when it is a dictionary.

**Comment by jrfonseca** [comment]
According to [this thread](https://www.kdpcommunity.com/s/question/0D5f400000FHSiTCAX/math-formula-formatting?language=en_US), it seems this _Enhanced Typesetting_ is not supported on older gen Kindles, but at least some e-ink Kindles do support it, per the last comment on that thread.

According to https://kdp.amazon.com/en_US/help/topic/G202087570:
> Enhanced Typesetting is supported on the following devices and applications:
> * Kindle E-readers 6th generation and newer
> * Fire tablets 3rd generation and newer
> * Kindle for iOS v4.9 or newer (iOS Versions: iOS 7, iOS 8 and iOS 9)
> * Kindle for Android v4.18.0 or newer (Android Versions: Jelly Bean, KitKat, Lollipop, and Marshmallow)

Per https://www.amazon.com/gp/help/customer/display.html?nodeId=GK33S847NN4V6Y83 it seems some Kindle Paperwhite are 6th-gen, others are 5-gen hence don't meet the cut...

I'll check mine.  I believe it's an early gen.

**Comment by jrfonseca** [comment]
> We already add an overline, but it is ignored by kindle when it is a dictionary.

Bummer...

**Comment by mymro** [comment]
I have an Oasis, which should support Advanced Typesetting, but even there it is ignored.
