### ISSUE TITLE
Update release

### ISSUE THREAD

**Issue by Thermospore** [jrfonseca/jmdict-kindle#30]
Hello, are you able to post a release of the current version (with the ぐ inflection fix etc)? Thanks for making this btw, I use it all the time

**Comment by jrfonseca** [comment]
My bad.  I tagged a release back in November 2022, but I now see I inadvertently left it as a _draft_, so it never got published.

Done now -- https://github.com/jmdict-kindle/jmdict-kindle/releases/tag/3.0.20230303

I'm glad to hear you find this useful.  Cheers.

**Comment by Thermospore** [comment]
Thanks so much, I'll check it out
