### ISSUE TITLE
Making other translation than english

### ISSUE THREAD

**Issue by ghost** [jrfonseca/jmdict-kindle#31]
Hello, could you help me with that? I don't understand programming.
I would like to final have a Japanese > Polish dictionary, but I don't know how to edit the source files where I can convert English to Polish to be able to final create a new dictionary on kindle that will work, I want you to explain it to me so I can already translate it myself

**Comment by jrfonseca** [comment]
jmdict-kindle uses dictionary database from https://www.edrdg.org/wwwjdic/wwwjdicinf.htmll .  There are dictionaries for languages other than English, but Polish is not one of them, so what you seek is not feasible.
