### ISSUE TITLE
Invert order of combined dictionary

### ISSUE THREAD

**Issue by Ceffa93** [jrfonseca/jmdict-kindle#6]
@jrfonseca 
I'm using the combined dictionary on a Kindle, and I noticed that the name lookups are always given as first result, before the regular dictionary lookups.

This is annoying in the case where a common word also happens to be a name. This is because 9 times out of 10, the regular dictionary definition is what you are actually looking for, and the name match is just a coincidence. After a few hours reading, I can report that this happens very frequently, forcing you to swipe after the name definition(s) until you get to the actual intended result.

It would be much better if the common words had precedence over the names, so the word is first looked up in the regular dictionary, and if it is not found there, as a fallback, it is looked up in the name dictionary.

Please, let me know your thoughts. Thanks for the great job!

**Comment by jrfonseca** [comment]
I haven't tried the combined dictionary myself. (To be honest, I've been slacking my Japanese reading for quite some time.)  But what you describes makes sense.

@mymro, you implemented the combined dictionary, what do you think?

I'm not even sure we can control precisely which entries Kindles picks first.  Another solution would be to merge both common word and name entries into a single entry.

**Comment by Ceffa93** [comment]
@jrfonseca 
Thank you for the answer. 

The kindle seems to always pick names first, so there must he some sort of information within the dictionary about which terms have precedence. 

As for merging the entries, that would not work well I think, some common words may have 10 or more entries. For example, selecting the kanji "一" now returns a bunch of names that happen to be read as ichi, and the actual number definition as the very last result. Merging all results would just create a very long result in which scrolling becomes necessary.

**Comment by mymro** [comment]
@Ceffa93 It has probably something to do with the order in which the terms are listed in the dictionary. I would have to look back into the code, but it might be that names are just added first. 

It would be great if you could look into this issue and figure out a solution. I am kind of buried in work right now, so I might not get to it right away.

Edit: I have noticed when the combined dictionary is built, the data from both dictionaries is combined, with the names being first. It is very likely this issue could be fixed, by just changing the order. I will try to build it with the different order and see what happens

**Comment by Ceffa93** [comment]
@mymro 
That was my guess as well, it really seemed just like names are added first. Please let me know if your fix is successful!

**Comment by mymro** [comment]
@Ceffa93  It should work now. I also added pronunciations. You can find the new files  [here](https://drive.google.com/drive/folders/1DZ99VpEWkpScbeFzVsnvLm4ZscZgQ6e2?usp=sharing)

Edit:I am still working on the pronunciation formatting

**Comment by Ceffa93** [comment]
@mymro  
Thank you for the update. I downloaded and tested the new combined dictionary, and I noticed a couple of problems:

- the order of the results is now seemingly undetermined. For example, considering the the kanji "一” which has 12 results in the regular dictionary and 19 results in the names dictionary, I get:
4 results from the regular dictionary, followed by 12 results form the names dictionary, followed by a few more regular entries, followed by several more names and so on. They don't see to be completely random, as they are somewhat "grouped", but they are also not in the expected order (i.e. all names last). I tested on a few more words and the inconsistencies are similar. In one case, all names were first, and the regular entries last, as was happening before.

- the definitions occasionally have some weird capitalization or arrows near them (which wasn't the case before). It might be related to the other open ticket, in that case just ignore this point.

**Comment by mymro** [comment]
@Ceffa93 The order is now as follows:
- First add all JMDICT entries
- Then add all JMNEDCT entries

I sort it the following way (I just prepend a 1 or 2 to the sorting word):
```
def sort_function(entry):
    if(entry.entry_type == VOCAB_ENTRY):
        return f"1-{entry.headword}"
    else:
        return f"2-{entry.headword}"
```

Any remaining Names that come in the beginning might be because they are in the JMDICT and not in the JMNEDICT. It could probably be fixed by diving into the tags of the JMDICT. I am not shure if I want to do that. Could you provide me with examples?

The capitalization should be fixed in the next upload. It was an attempt of formatting pronunciations. Now it is done with underlines

**Comment by mymro** [comment]
@Ceffa93 I have looked at the [mobi style guide](https://kindlegen.s3.amazonaws.com/AmazonKindlePublishingGuidelines.pdf) again and it looks like the kindle itself creates an index, based on the terms and its inflections, and does fuzzy searching. This means I have little influence over the order in which terms appear

**Comment by mymro** [comment]
I have looked again an there is a defaultindex element. I am not sure if it works and before I can test it I have to reduce each entry by 8 characters. Otherwise it won't build (passes beyond the 650MB mark).

**Comment by mymro** [comment]
@Ceffa93  please find the newest compiled dictionaries [here](https://drive.google.com/drive/folders/1DZ99VpEWkpScbeFzVsnvLm4ZscZgQ6e2?usp=sharing) The ordering did not work. i did howerver manage to reduce the size and add example sentences.

**Comment by Ceffa93** [comment]
@mymro 
Thank you, I'll test the dictionary later. 
As for the names, I did check if they were actually in the JMDICT, but that wasn't the case, they were all JMNDICT and the ordering was random.

**Comment by mymro** [comment]
@Ceffa93 I can't tell kindle  which words to list first. At least I can't find a way. If I use indices only entries in the default one are displayed. Maybe somebody else has an idea on how to fix this, but it seems highly unlikely. @jrfonseca for now I would close this issue
