### ISSUE TITLE
Add Pitch information from https://github.com/mifunetoshiro/kanjium

### ISSUE THREAD

**Issue by mymro** [jrfonseca/jmdict-kindle#8]
This dictionary currently uses pitch information from one source. [mifunetoshiro/kanjium](https://github.com/mifunetoshiro/kanjium)  has around 125.000  words with pitch information.  It would increase the entries with accent data dramatically

**Comment by gitdubblub** [comment]
The Japanese learning community at Refold Japanese discord would greatly appreciate pitch accent information on Paperwhite.. any hopes for integration?

**Comment by mymro** [comment]
@gitdubblub Pitch accent information is already present in newer releases of the dictionary. Maybe I will look into integrating the additional information around Christmas

**Comment by gitdubblub** [comment]
The importance of pitch is becoming more aware in the community, so we
still look forward to the pitch being added to the Kindle dictionary.
Thanks for not dropping the project.

2022年1月20日(木) 10:39 José Fonseca ***@***.***>:

**Comment by mymro** [comment]
@gitdubblub There is already pitch information present in the dictionary and the additional pitch information has been added. Please download the [newest version here](https://github.com/jmdict-kindle/jmdict-kindle/releases).

For information on how the pitch information is encoded, please look into the [README](https://github.com/jmdict-kindle/jmdict-kindle/blob/master/README.md#pitch-accent-information). Please note, the combined dictionary (combined.mobi) does not contain pitch information and other features due to size constraints.

**Comment by gitdubblub** [comment]
> @gitdubblub There is already pitch information present in the dictionary and the additional pitch information has been added. Please download the [newest version here](https://github.com/jmdict-kindle/jmdict-kindle/releases).
> 
> For information on how the pitch information is encoded, please look into the [README](https://github.com/jmdict-kindle/jmdict-kindle/blob/master/README.md#pitch-accent-information). Please note, the combined dictionary (combined.mobi) does not contain pitch information and other features due to size constraints.

Thank you so much mymro! Indeed the jmdict.mobi file has pitch information but not the combined.mobi. Maybe you can update that too?

**Comment by mymro** [comment]
@gitdubblub Unfortunately adding this information to the combined dictionary appears to currently not be possible. There is a hard limit to how big a mobi can get and adding pronuctioation will push the file past the limit.

**Comment by jrfonseca** [comment]
@mymro is there some database of Japanese's word frequency?  One could use such frequency database to create a smaller combined dictionary, with all bells and whistles, for the most frequent words, so that it stays under the size limit.  Seems the best way to have the cake and eat it...

**Comment by PMF-Constantin** [comment]
@jrfonseca There is frequency data in this [repo](https://github.com/mifunetoshiro/kanjium) and you can find more probably somewhere else

**Comment by mymro** [comment]
@jrfonseca I am not a fan of taking words out of the dictionary. You will always have some arbitrary cut off point. The lower the cut off point the less likely it is that one word will not be found. However there is always a possibility of a word not being found due to the missing data.

In my opinion we should get rid of the combined dictionary. It is not really useful for reading anyway. When you look up words very often the first thing you see are names instead of words. You then have to tap through multiple pages until you find the entry you are actually looking for. Also, the few names you do see in books you will inevitably remember at some point.

**Comment by jrfonseca** [comment]
Before digital dictionaries were a thing, it was common for dictionaries of different sizes: some pocket, some multiple volumes.  It's still true today if one buys paper dictionaries.  It's a perfectly acceptable trade-off between convenience and completeness.

I haven't used these dictionaries myself in a while, so I don't have an opinion about combined dictionary.  I'm happy to be guided by you.

That said, it does seem that some users tend to use up the combined.  I don't know if it's a true preference or merely rhethe result misleading naming, as out of the three mobi files available for downlioad _combined_ does sound the best.   So, even if we keep combined dict, maybe we should rename it to make it clear that it's not the exact combination of those two, e.g, `combined_jmdict_jmndict_nopitch_fewerexamples`.

Or we add a _Which dictionary should I use?_ table to the README, with a side-by-side comparison of the three, dictionaries, so folks can choose.

**Comment by mymro** [comment]
@jrfonseca I am in favour of remaining the combined dictionary. We cannot rely on people reading the README. I also thought about splitting the combined dictionary, but I do not have frequency information for names and those would have to be split too. They make up the majority of entries in the combined dictionary. Of course we could always put all names including the most frequent words in part one and the remaining words in part two. However it does not seem right to me having a second part without names

**Comment by gitdubblub** [comment]
Thanks man, it's such a blessing to finally have Japanese English
dictionary with pitch info for the Kindle paperwhite! I'm really loving it.

2022年2月8日(火) 15:52 mymro ***@***.***>:
